ccflags-y += -I$(srctree)/drivers/misc/mediatek/magnetometer/inc
ccflags-y += -I$(srctree)/drivers/misc/mediatek/hwmon/include
ccflags-y += -I$(srctree)/drivers/misc/mediatek/accelerometer/inc
ccflags-y += -I$(srctree)/drivers/misc/mediatek/sensorHub/inc
ccflags-y += -I$(srctree)/drivers/misc/mediatek/gyroscope/inc
obj-y	:=  afx133.o
